user_name = input("Enter your name")
user_second_name = input("Enter your second name")
user_surname = input("Enter your surname")
user_age = input("Enter your age")
user_age = int(user_age)
print(type(user_name))
print(type(user_second_name))
print(type(user_surname))
print(type(user_age))
